version: '3.8'

services:
  create_deck:
    build:
      context: .
      dockerfile: Dockerfile.create_deck
    container_name: 2anki-create-deck
    volumes:
      - genanki-workspace:/tmp/genanki
      - server-templates:/app/server/src
      - create-deck-scripts:/app/create_deck
    networks:
      - anki-network
    depends_on:
      - server
    environment:
      - TMPDIR=/tmp/genanki
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: 2anki-server
    ports:
      - "2020:2020"
    volumes:
      - genanki-workspace:/tmp/genanki
      - web-build:/app/server/web/build
      - server-templates:/app/server/src
      - create-deck-scripts:/app/create_deck
    networks:
      - anki-network
    depends_on:
      - web
    environment:
      - WORKSPACE_BASE=/tmp/genanki
      - TMPDIR=/tmp/genanki
      - ADDITIONAL_ALLOWED_ORIGINS=${ADDITIONAL_ALLOWED_ORIGINS:-}
      - ALLOWED_IP_ADDRESSES=${ALLOWED_IP_ADDRESSES:-}
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: 2anki-web
    volumes:
      - web-build:/app/server/web/build
    networks:
      - anki-network

volumes:
  genanki-workspace:
    driver: local
  web-build:
    driver: local
  server-templates:
    driver: local
  create-deck-scripts:
    driver: local

networks:
  anki-network:
    driver: bridge
