name: Build and Push Docker Images

on:
  push:
    paths:
      - '**/Dockerfile'
      - '**/Dockerfile.*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Clone 2anki repositories
      run: |
        git clone https://github.com/2anki/server
        git clone https://github.com/2anki/web
        git clone https://github.com/2anki/create_deck
    
    - name: Build and push Web image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.web
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/2anki-web:latest
    
    - name: Build and push Create Deck image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.create_deck
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/2anki-create-deck:latest
    
    - name: Build and push Server image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.server
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/2anki-server:latest